version: 2
models: 
  - name: view_users
    description: "A view that breaks down user address information into separate columns for address, city, state, zip, and country, in addition to providing user identity and contact information. This transformation facilitates easier analysis and segmentation of users by geographic location."
    columns:
      - name: id
        description: "The unique identifier for the user."
      - name: first_name
        description: "The first name of the user."
      - name: last_name
        description: "The last name of the user."
      - name: email
        description: "The email address of the user."
      - name: signup_date
        description: "The date the user signed up."
      - name: address
        description: "The street address portion of the user's full address."
      - name: city
        description: "The city portion of the user's full address."
      - name: state
        description: "The state portion of the user's full address."
      - name: zip
        description: "The ZIP code portion of the user's full address."
      - name: country
        description: "The country portion of the user's full address."
