version: 2
models: 
  - name: view_products
    description: "A view that enriches product data by correcting category names and providing a cleaned-up, user-friendly presentation of products. This includes product IDs, names, normalized category names, prices, and quantities in stock."
    columns:
      - name: product_id
        description: "The unique identifier for the product."
      - name: product_name
        description: "The name of the product."
      - name: category
        description: "The category of the product, with corrections applied for consistency and readability. Categories include 'Electronics', 'Home & Kitchen', and 'Books', with other categories passed through unchanged."
      - name: price
        description: "The price of the product."
      - name: qty_in_stock
        description: "The quantity of the product currently in stock."
